apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-demo
  template:
    metadata:
      name: config-demo
      labels:
        app: config-demo
    spec:
      volumes:
      - name: config
        configMap:
          name: app-config
          items:
          - key: FILE_ENV
            path: cfg

      containers:
      - name: config
        image: docker.ops.iszn.cz/jan.drazil/k8sdemo/config:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: "/config"
        env:
        - name: DEPLOYMENT_ENV
          value: "deployment-base"
        - name: FILE_COMMON
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: COMMON
