apiVersion: apps/v1
kind: Deployment
metadata:
  name: comm-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comm-server
  template:
    metadata:
      name: comm-server-pod
      labels:
        app: comm-server
    spec:
      containers:
      # Serves static pages from /usr/share/nginx/html
      - name: nginx
        image: nginx:1.21.1

      # Generates static pages with counter
      - name: data-generator
        image: data-generator:v1

      # Logs pages served by nginx
      - name: local-client
        image: http-client:v1
