apiVersion: apps/v1
kind: Deployment
metadata:
  name: comm-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comm-server
  template:
    metadata:
      name: comm-server-pod
      labels:
        app: comm-server
    spec:
      # Defines available volumes
      volumes:
      - name: html-root
        emptyDir: { }

      containers:
      # Serves static pages from /usr/share/nginx/html
      - name: nginx
        image: nginx:1.21.1
        # Mounts html-root into /usr/share/nginx/html in the container
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-root

      # Generates static pages with counter
      - name: data-generator
        image: data-generator:v1
        # Mounts html-root into /data in the container
        volumeMounts:
        - mountPath: /data
          name: html-root

      # Logs pages served by nginx
      - name: local-client
        image: http-client:v1
        env:
        - name: TARGET
          value: localhost
