# Expose the deployment into k8s for others pods
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    app: comm-server
  ports:
  - name: http
    port: 80
    targetPort: 80
