apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kustomize
spec:
  template:
    spec:
      containers:
      - name: config
        env:
        - name: DEPLOYMENT_ENV
          value: "deployment-overlay"
