apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: counter-dep
  template:
    metadata:
      name: counter-pod
      labels:
        app: counter-dep
    spec:
      containers:
      - name: counter-container
        image: docker.ops.iszn.cz/jan.drazil/k8sdemo/counter:v2
