apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Mi

---

apiVersion: v1
kind: Service
metadata:
  name: my-statefultset-service
spec:
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefultset
spec:
  replicas: 3
  serviceName: my-statefultset-service
  selector:
    matchLabels:
      app: counter-sts
  template:
    metadata:
      name: counter-pod
      labels:
        app: counter-sts
    spec:
      containers:
      - name: counter-container
        image: docker.ops.iszn.cz/jan.drazil/k8sdemo/counter:v1
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo-claim
