apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: counter-container
        image: docker.ops.iszn.cz/jan.drazil/k8sdemo/dump-env:v1
