apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cool-counter
  template:
    metadata:
      name: cool-counter
      labels:
        app: cool-counter
    spec:
      containers:
      - name: counter-container
        image: counter:v2
