apiVersion: v1
kind: Service
metadata:
  name: counter-sts
spec:
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-counter
spec:
  replicas: 3
  serviceName: counter-sts
  selector:
    matchLabels:
      app: counter-sts
  template:
    metadata:
      name: counter-pod
      labels:
        app: counter-sts
    spec:
      containers:
      - name: counter-container
        image: counter:v1
