apiVersion: batch/v1
kind: Job
metadata:
  name: dump-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: counter-container
        image: dump-env:one-shot
