apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: counters-everywhere
spec:
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      name: counter-pod
      labels:
        app: counter
    spec:
      containers:
      - name: counter-container
        image: counter:v1
