apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  cfg-file: /app/k8s.cfg
  custom-config: |
    This is custom config
    Try to change me
  another-config: |
    This is another config
  unused-config: |
      This is another config
