apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  cfg-file: /app/k8s.cfg
  custom-config: |
    This is custom config
    Try to change me
  another-config: |
    This is another config
  unused-config: |
      This is another config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-reader
spec:
  selector:
    matchLabels:
      app: config-reader
  template:
    metadata:
      name: config-reader
      labels:
        app: config-reader
    spec:
      # Specify sources for mounting into container
      volumes:
      # Creates a volume with nginx config from nginx-config ConfigMap
      - name: config-volume
        configMap:
          name: app-config
          items:
          - key: custom-config
            path: k8s.cfg
          - key: another-config
            path: another.cfg

      containers:
      - name: config-reader
        image: read-cfg:v1
        volumeMounts:
        # Mount volume specified in volumes with config
        - name: config-volume
          mountPath: /app
        env:
        # Set environment variable CFG_FILE with value pointing to config mounted in the pod
        - name: CFG_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cfg-file
