# NGINX config with server exposing secrets
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-secret-config
data:
  secrets-interface: |
    server {
      listen       81;
      listen  [::]:81;
      server_name  localhost;
    
      location / {
          expires -1;
          root   /usr/share/nginx/secrets;
          index  secrets.html;
      }
    
      location = /secret {
        expires -1;
        default_type text/plain;
        return 200 "${SECRET_ENV}";
      }
    
      location = /sasanka {
        expires -1;
        default_type text/plain;
        return 200 "${SASANKA_SECRET}";
      }
    }

---

# Kubernetes secret propagated into nginx conf file and as standalone file
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
stringData:
  secretEnv: "Foo Bar\\n"
  secretPage: "<h1>Secret Page</h1><a href=\"/secret\">Env Secret</a><br/><a href=\"/sasanka\">Env Sasanka Secret</a>"

---

# Deployment with nginx exposing secrets

# REQUIRES secret from sasanka
# secret name: sasanka-secret
# secret values:
# - token

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      name: config-server-pod
      labels:
        app: config-server
    spec:
      # Specify sources for mounting into container
      volumes:
      # Creates a volume with nginx config from server-secret-config ConfigMap
      - name: secret-interface
        configMap:
          name: server-secret-config
          items:
          - key: secrets-interface
            path: secrets.conf.template
      # Creates a volume with secret page from server-secret Secret
      - name: secrets
        secret:
          secretName: server-secret
          items:
          - key: secretPage
            path: secrets.html

      containers:
      - name: nginx
        image: docker.ops.iszn.cz/upstream/nginx/nginx:1.21.1
        env:
        # Set environment variable SECRET_ENV with value from server-secret Secret
        - name: SECRET_ENV
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: secretEnv
        # Set environment from secrets synced through sasanka
        - name: SASANKA_SECRET
          valueFrom:
            secretKeyRef:
              name: sasanka-secret
              key: token
        volumeMounts:
        # Mount volume specified in volumes with nginx config
        - name: secret-interface
          mountPath: /etc/nginx/templates
        # Mount volume specified in volumes with secret page
        - name: secrets
          mountPath: /usr/share/nginx/secrets

---

# Creates endpoints
apiVersion: v1
kind: Service
metadata:
  name: config-demo-server
spec:
  selector:
    app: config-server
  ports:
  - name: http
    port: 80
  - name: secret
    port: 81
